name: drift_tuts
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  drift: ^1.6.0
  sqlite3_flutter_libs: ^0.5.9
  path_provider: ^2.0.11
  path: ^1.8.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  drift_dev: ^1.6.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
